title: Shallow and Pedantic
email: ohad@lutzky.net
description: &description >-
  A personal/tech/code blog of a coder/techie/person. Like calculus in a kiddie
  pool, the author of this blog is known to be quite shallow and pedantic.
twitter_username: lutzky
github_username: lutzky
minimal_mistakes_skin: default
search: true

# Build settings
markdown: GFM
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: pretty
paginate: 5 # amount of posts to show
paginate_path: /page:num/

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - run_local.sh
  - README.md

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name: "Ohad Lutzky"
  avatar: "/assets/images/bio-photo.jpg"
  bio: *description
  links: &social-links
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/lutzky"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter"
      url: "https://twitter.com/lutzky"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook"
      url: "https://facebook.com/lutzky"

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "UA-40939561-1"

social:
  type: Person
  links:
    - "https://github.com/lutzky"
    - "https://twitter.com/lutzky"
    - "https://facebook.com/lutzky"

footer:
  links: *social-links

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      show_date: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
