# Site settings
title: Shallow and Pedantic
email: ohad@lutzky.net
description: >-
  A personal/tech/code blog of a coder/techie/person. Like calculus in a kiddie
  pool, the author of this blog is known to be quite shallow and pedantic.
baseurl: ""
url: "http://lutzky.github.io"
twitter_username: lutzky
github_username:  lutzky
google_analytics: UA-40939561-1
permalink: pretty

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
