baseURL: https://lutzky.net
disablePathToLower: true
languageCode: en-us
title: Shallow and Pedantic
theme: PaperMod

frontmatter:
  # Grab date AND SLUG from filename - undocumented, but
  # see https://github.com/gohugoio/hugo/pull/4494/
  date: [":filename", ":default"]

permalinks:
  posts: /:year/:month/:day/:slug/

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  author: "Ohad Lutzky"
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  disableSpecial1stPost: true

  homeInfoParams:
    Title: Ohad Lutzky
    Content: >
      A person/tech/code blog of a coder/techie/person. Like calculus in a
      kiddie pool, the author of this blog is known to be quite shallow and
      pedantic.

  socialIcons:
    - name: "github"
      url: "https://github.com/lutzky/"
    - name: "facebook"
      url: "https://facebook.com/lutzky/"

menu:
  main:
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: search
      name: Search
      url: /search/
      weight: 20
    - identifier: archive
      name: Archive
      url: /archives/
      weight: 20
